baseurl = "https://example.com"
enableEmoji = true
footnotereturnlinkcontents = "↩"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-classic"
title = "Classic"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4


[caches]
  [caches.images]
    dir = ":cacheDir/images"

[permalinks]
post = "/post/:year/:month/:day/:slug/"


[[menu.main]]
name = "Musik"
url = "/musik/"
weight = 1

[[menu.main]]
name = "Wichtig ❤️"
url = "/wichtig/"
weight = 2

[[menu.main]]
name = "Essen & Trinken"
url = "/verpflegung/"
weight = 3

[[menu.main]]
name = "Mitnehmen"
url = "/packen/"
weight = 4

[[menu.main]]
name = "Anreisen"
url = "/anreisen/"
weight = 5


[params]
custom_css = ["css/theme-override.css"]
description = "A simple, minimal blog for those who love text."
footer = "Open-Source | [Github](https://github.com/goodroot/hugo-classic) | [Keybase](https://keybase.io/goodroot)"
